//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uch
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class uchprEntities1 : DbContext
    {
        public uchprEntities1()
            : base("name=uchprEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AuthorRequests> AuthorRequests { get; set; }
        public virtual DbSet<Books> Books { get; set; }
        public virtual DbSet<FreezeAppeals> FreezeAppeals { get; set; }
        public virtual DbSet<Genres> Genres { get; set; }
        public virtual DbSet<Reports> Reports { get; set; }
        public virtual DbSet<Reviews> Reviews { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<UserBookLists> UserBookLists { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
