//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uch
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reports
    {
        public int Id { get; set; }
        public int ReporterId { get; set; }
        public Nullable<int> BookId { get; set; }
        public Nullable<int> ReviewId { get; set; }
        public string Reason { get; set; }
        public bool IsResolved { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual Books Books { get; set; }
        public virtual Users Users { get; set; }
        public virtual Reviews Reviews { get; set; }
    }
}
